### ISSUE TITLE
Error clicking "Normal items"

### ISSUE THREAD

**Issue by Lejving** [anoutsider/advanced-logistics-system#17]
```
Error while running event on_gui_click (ID 1)
Unknown style item-icons-effectivity-module
stack traceback:
    __advanced-logistics-system__/gui/items.lua:127: in function 'updateItemsTable'
    __advanced-logistics-system__/gui/main.lua:86: in function 'updateGUI'
    __advanced-logistics-system__/gui/events.lua:68: in function <__advanced-logistics-system__/gui/events.lua:2>
```

Another similar error:

```
Unknown style item-icons-repair-pack
stack traceback:
    __advanced-logistics-system__/gui/items.lua:127: in function 'updateItemsTable'
    __advanced-logistics-system__/gui/main.lua:83: in function 'updateGUI'
    __advanced-logistics-system__/gui/events.lua:726: in function <__advanced-logistics-system__/gui/events.lua:2>


Another error but this time on page two of network items. I have a lot of mods but afaik nothing that changes any icons for repair pack nor effectivity module :(
```

With my extremely terrible knowledge of programming, it seems that effectivity-module and repair-pack are not items. The first should be "module-icons-effectivity-module" and the second one "repair-tool-icons-repair-pack" or possibly "demo-item-icons-repair-pack" (haha I don't know). Hope this helps somewhat

@spencersutton

**Comment by Lejving** [comment]
Unknown style item-icons-repair-pack
stack traceback:
	__advanced-logistics-system__/gui/items.lua:127: in function 'updateItemsTable'
	__advanced-logistics-system__/gui/main.lua:83: in function 'updateGUI'
	__advanced-logistics-system__/gui/events.lua:726: in function <__advanced-logistics-system__/gui/events.lua:2>


Another error but this time on page two of network items. I have a lot of mods but afaik nothing that changes any icons for repair pack nor effectivity module :(

**Comment by spencersutton** [comment]
Thanks for reporting this. Turns out my fix for the battery icon broke icons for a ton of stuff, I reverted the change and uploaded a [new zip file](https://github.com/spencersutton/advanced-logistics-system/releases/download/0.2.14/advanced-logistics-system_0.2.14.zip).

Also you can open issues on my fork now, I didn't know you had to enable that manually.

I can't close this issue because it's not on my repo, so you probably should since it doesn't apply to this repo. That is if you can close your own issues.
