### ISSUE TITLE
Module crashes with "attempt to index field '?'" error

### ISSUE THREAD

**Issue by ChurchOrganist** [anoutsider/advanced-logistics-system#18]
Trying to run the module in Factorio 0.13.15 results in a crash with the following error......

Error while running the on_init:**advanced-logistics-system**/control.lua:830:attempt to index field '?' (a nil value)

So somethings not getting initialised properly somewhere. I've had a brief look, but can't spot anything obvious, unless it's a clash with one of my other mods: Agent Orange 0.06, Bergius_Process 0.1.2, Big_Brother 0.3.2, DoubleReach 0.13.1, EvoGUI 0.4.107, Foreman 0.2.4, KS_Power 0.1.5, Reinforced-Walls 0.2.3, Spawn_Gear 0.1.6 YARM 0.7.104, fluid-barrel 1.1.1, no-more-redundancies 0.1.1, rso-mod 2.0.11

PS I've just tried with only Advanced Logistics System enabled and get the same error.

**Comment by spikerwork** [comment]
I have the same error when using Factorio 0.13.19 and mods:
AutoDeconstruct_0.1.4, BlackMarket_1.0.13 , all bob's mods for 0.13, clock_0.13.0 , EvoGUI_0.4.107, evo_elev_temp_0.0.3, Factorissimo_0.1.6 , FARL_0.5.36 , ItemsGenerators_0.0.1 , Larger Inventory_1.0.1 , long-reach_0.0.5 , MoreLight_1.1.1 , robotarmy_0.2.2 , SmallFixes_0.1.2 , tree_collision_0.3.0 , upgrade-planner_1.2.4 , YARM_0.7.105. Disabling all mods doesn`t fix problem.

PS. Also, another small problem — when you downloading advanced-logistics-system from github as zip, factroio can`t start because the folder in zip archive must have named "advanced-logistics-system_0.3.0"

PSS. For fix this problem i added  
`if index == '?' and type == nil then 
    index = 1   
end`
to contol.lua in the begining of the function _getLogisticsItems_. 
Everything works fine now.
